### PR TITLE
Removing support statement for aws EFS storage from documents.

### PR DESCRIPTION
**Pull request by satyamodi**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by parthakom2** [comment]
@vsnyc @annaone can this doc change be reviewed and merged. thanks.

**Review by annaone — APPROVED** [review]

**Comment by annaone** [comment]
> @vsnyc @annaone can this doc change be reviewed and merged. thanks.

Approved and merged!

**Comment by parthakom2** [comment]
Thanks.

@vsnyc can the doc change be merged to master. thanks!

**Comment by prsahoo** [comment]
@annaone @vsnyc  These changes still do not show up on Quick Start page for IBM Cloud Pak for data.   https://aws-quickstart.github.io/quickstart-ibm-icp-for-data/#_ibm_cloud_pak_for_data_on_aws

Can you please help to publish the updates ?  Thank you.

**Comment by annaone** [comment]
@prsahoo - let me look into this. I thought this update was merged months ago.

**Pull request merged**
