### PR TITLE
Phase 2 changes of IBM cloud pak for data

### PR DESCRIPTION
**Pull request by shaithal**
*Issue #, if available:*

*Description of changes:*

- Add node feature

- Addons - Data virtualization, DSX premium and Db2 warehouse

- Rebranding changes

- More options for worker node instance types

- Added ICP console url to root output

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shaithal** [comment]
@vsnyc @parthakom2

**Comment by shaithal** [comment]
[taskcat_outputs.zip](https://github.com/aws-quickstart/quickstart-ibm-icp-for-data/files/3328410/taskcat_outputs.zip)

**Comment by vsnyc** [comment]
Ran into the following error when testing. `icpd_bootstrap.py` bundled in `aws-icpd-bootstrap.zip` has a typo in `activate-license.sh`: ` source_file = open("/root/acitvate-license.sh").read()`

```
[19/07/03 08:12:04.632439 UTC] 7ff518b39700 I __main__(147) installICPD : IBM Cloud Pak for Data installation completed.
[19/07/03 08:12:04.632525 UTC] 7ff518b39700 E __main__(274) main : ERROR: [Errno 2] No such file or directory: '/root/acitvate-license.sh'
	[Errno 2] No such file or directory: '/root/acitvate-license.sh'
	Exception stack (most recent call first):
	icpd_bootstrap.py(149) [installICPD] - source_file = open("/root/acitvate-license.sh").read()
	icpd_bootstrap.py(269) [main] - self.installICPD()
	Frame stack (most recent call first):
	icpd_bootstrap.py(274) [main] - TR.error(methodName,"ERROR: %s" % e, e)
	icpd_bootstrap.py(326) [<module>] - mainInstance.main(sys.argv)
[19/07/03 08:12:04.636426 UTC] 7ff518b39700 1 yapl.aws.LogExporter(99) exportLogs : Exporting log: /opt/icp/3.1.2/cluster/logs/install.log.20190703052740 to S3: cftests:logs/tCaT-tag-icpd-ha-dns-us-east-1-9a1d11bc/boot/ip-10-10-20-98.ec2.internal/install.log.20190703052740
[19/07/03 08:12:04.806014 UTC] 7ff518b39700 I __main__(299) main : BOOT0104I FAILED END Boostrap AWS ICPD Quickstart.  Elapsed time (hh:mm:ss): 1:32:39
```

**Comment by shaithal** [comment]
@vsnyc  updated the aws-icpd-bootstrap.zip package

**Pull request merged**
